import { defineConfig, presetIcons, presetUno } from 'unocss'

export default defineConfig({
  presets: [
    presetUno(),
    presetIcons({
      scale: 1.1,
      extraProperties: {
        display: 'inline-block',
        'vertical-align': 'middle',
      },
    }),
  ],
  theme: {
    fontFamily: {
      body: '"Manrope", "Noto Sans SC", sans-serif',
      headline: '"Space Grotesk", "Noto Sans SC", sans-serif',
      label: '"Manrope", "Noto Sans SC", sans-serif',
      mono: '"SFMono-Regular", "JetBrains Mono", monospace',
    },
    colors: {
      background: '#f4f7f3',
      surface: '#fffdf8',
      'surface-container-lowest': '#ffffff',
      'surface-container-low': '#f4f7fb',
      'surface-container-high': '#e7eef1',
      'surface-container-highest': '#d8e5e7',
      primary: '#4D0099',
      'primary-dim': '#36006b',
      'primary-container': '#e4ccff',
      'on-primary': '#ffffff',
      'on-primary-container': '#1a0033',
      secondary: '#c67a00',
      'secondary-container': '#fde7be',
      'on-secondary-container': '#6b3e00',
      tertiary: '#8b5cf6',
      'tertiary-container': '#e8ddff',
      'on-tertiary-container': '#4f2bb7',
      error: '#dc2626',
      'on-error': '#fff5f5',
      outline: '#9eb0b2',
      'outline-variant': '#b9c9ca',
      headline: '#0f172a',
      'on-background': '#18323a',
      'on-surface': '#17313b',
      'on-surface-variant': '#5d7480',
    },
    boxShadow: {
      soft: '0 18px 45px rgba(15, 23, 42, 0.08)',
      card: '0 20px 50px rgba(15, 118, 110, 0.08)',
    },
  },
  shortcuts: {
    'primary-gradient':
      'bg-gradient-to-br from-primary via-[#6B00CC] to-primary-dim shadow-[0_18px_50px_rgba(77,0,153,0.28)]',
    'ghost-border': 'border border-outline-variant/28',
    'text-headline': 'text-headline',
  },
  safelist: [
    'bg-background',
    'bg-surface',
    'bg-surface-container-lowest',
    'bg-surface-container-low',
    'bg-surface-container-high',
    'bg-surface-container-highest',
    'text-on-background',
    'text-on-surface',
    'text-on-surface-variant',
    'text-on-primary',
    'text-on-primary-container',
    'text-on-secondary-container',
    'text-on-tertiary-container',
    'bg-primary',
    'bg-primary-dim',
    'bg-primary-container',
    'bg-secondary',
    'bg-secondary-container',
    'bg-tertiary',
    'bg-tertiary-container',
    'border-outline-variant/15',
    'border-outline-variant/20',
    'font-body',
    'font-headline',
    'font-label',
    'primary-gradient',
    'ghost-border',
  ],
})
