# 配置仅供参考！
workflow:
  rules:
    - when: always

stages:
  - quality
  - build

cache:
  key: "frontend-${CI_COMMIT_REF_SLUG}"
  paths:
    - frontend/node_modules/

frontend-lint:
  stage: quality
  image: node:20
  rules:
    - when: on_success
  script:
    - cd frontend
    - npm ci
    - npm run lint

frontend-build:
  stage: build
  image: node:20
  rules:
    - when: on_success
  needs:
    - frontend-lint
  script:
    - cd frontend
    - npm ci
    - npm run build
  artifacts:
    when: on_success
    paths:
      - frontend/dist/
